# Generated by Django 4.2.11 on 2024-08-26 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('polyline', models.TextField(null=True)),
                ('ride_date', models.DateField(default=django.utils.timezone.now)),
                ('ride_time', models.TimeField(default=django.utils.timezone.now)),
                ('car_model', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_date', models.DateField(default=django.utils.timezone.now)),
                ('ride_time', models.TimeField(default=django.utils.timezone.now)),
                ('start_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('polyline', models.TextField()),
                ('distance', models.FloatField(default=0.0)),
                ('ride_giver_start', models.CharField(max_length=255)),
                ('ride_giver_destination', models.CharField(max_length=255)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool_app.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideGiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(choices=[('Alto', 'Alto'), ('Wagon R', 'Wagon R'), ('Swift', 'Swift'), ('Dzire', 'Dzire'), ('Baleno', 'Baleno'), ('Brezza', 'Brezza'), ('Grand Vitara', 'Grand Vitara'), ('Ciaz', 'Ciaz'), ('XL6', 'XL6'), ('Eeco', 'Eeco'), ('Grand i10 Nios', 'Grand i10 Nios'), ('i20', 'i20'), ('Creta', 'Creta'), ('Venue', 'Venue'), ('Verna', 'Verna'), ('Alcazar', 'Alcazar'), ('Kona Electric', 'Kona Electric'), ('Seltos', 'Seltos'), ('Carens', 'Carens'), ('Sonet', 'Sonet'), ('EV6', 'EV6'), ('Nexon', 'Nexon'), ('Innova', 'Innova'), ('Punch', 'Punch'), ('Tiago', 'Tiago'), ('Harrier', 'Harrier'), ('Safari', 'Safari'), ('Nexon EV', 'Nexon EV'), ('Scorpio', 'Scorpio'), ('Thar', 'Thar'), ('XUV700', 'XUV700'), ('Bolero', 'Bolero'), ('XUV300', 'XUV300'), ('Fortuner', 'Fortuner'), ('Innova Crysta', 'Innova Crysta'), ('Camry', 'Camry'), ('Corolla Altis', 'Corolla Altis'), ('City', 'City'), ('Amaze', 'Amaze'), ('WR-V', 'WR-V'), ('Civic', 'Civic'), ('Magnite', 'Magnite'), ('Kicks', 'Kicks'), ('Kushaq', 'Kushaq'), ('Slavia', 'Slavia'), ('Octavia', 'Octavia'), ('Taigun', 'Taigun'), ('Polo', 'Polo'), ('C-Class', 'C-Class'), ('E-Class', 'E-Class'), ('3 Series', '3 Series')], max_length=50)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], default='Petrol', max_length=20)),
                ('features', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool_app.ridegiver'),
        ),
    ]
