# Generated by Django 4.2.11 on 2024-08-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='car_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
