# Generated by Django 4.2.11 on 2024-08-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0002_riderequest_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='car_model',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
