# Generated by Django 4.2.11 on 2024-08-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0003_alter_riderequest_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridegiver',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ridegiver',
            name='mobile_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='requested', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='ridegiver',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_ridegiver_user'),
        ),
    ]
