# Generated by Django 4.2.11 on 2024-08-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0004_ridegiver_account_balance_ridegiver_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='polyline',
            field=models.TextField(null=True),
        ),
    ]
