# Generated by Django 4.2.11 on 2024-08-28 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0007_alter_userprofile_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('completed', 'Completed')], default='joined', max_length=10)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool_app.riderequest')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool_app.ride')),
            ],
        ),
    ]
