# Generated by Django 4.2.11 on 2024-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0008_joinedride'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
