# Generated by Django 4.2.11 on 2024-09-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0009_riderequest_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderequest',
            old_name='account_balance',
            new_name='cost',
        ),
    ]
