# Generated by Django 4.2.11 on 2024-09-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0010_rename_account_balance_riderequest_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('joined', 'Joined'), ('completed', 'Completed')], default='requested', max_length=10),
        ),
    ]
