# Generated by Django 4.2.11 on 2024-12-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0012_userprofile_is_verified_userprofile_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_created_at',
        ),
    ]
