# Generated by Django 4.2.11 on 2024-12-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0013_remove_userprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridegiver',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='ridegiver',
            name='vehicle_number',
            field=models.CharField(default='KL 34A 7617', max_length=15),
        ),
    ]
