# Generated by Django 4.2.11 on 2025-01-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0018_alter_ridegiver_car_alter_ridegiver_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridegiver',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('ev', 'ev'), ('hybrid', 'hybrid')], default='petrol', max_length=20),
        ),
    ]
