# Generated by Django 4.2.11 on 2025-02-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0021_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='seats_offered',
            field=models.IntegerField(default=1),
        ),
    ]
