# Generated by Django 4.2.11 on 2025-02-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0022_ride_seats_offered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='seats_offered',
            new_name='number_of_seats',
        ),
    ]
