# Generated by Django 4.2.11 on 2025-02-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0023_rename_seats_offered_ride_number_of_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='number_of_seats',
        ),
    ]
