# Generated by Django 4.2.11 on 2025-02-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0024_remove_ride_number_of_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='seats_available',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
