# Generated by Django 4.2.11 on 2025-02-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0025_ride_seats_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='seats_available',
            field=models.IntegerField(default=4),
        ),
    ]
