# Generated by Django 4.2.11 on 2025-02-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0026_alter_ride_seats_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='seats_available',
            new_name='seats_offered',
        ),
    ]
